create extension if not exists pgcrypto;

create table if not exists public.user_profiles (
  user_id text primary key,
  plan text not null default 'free'
    check (plan in ('free', 'starter', 'growth', 'pro')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.campaign_usage (
  id bigint generated by default as identity primary key,
  user_id text not null,
  month_key text not null check (month_key ~ '^\d{4}-\d{2}$'),
  usage_count integer not null default 0 check (usage_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, month_key)
);

create table if not exists public.poster_usage (
  id bigint generated by default as identity primary key,
  user_id text not null,
  month_key text not null check (month_key ~ '^\d{4}-\d{2}$'),
  usage_count integer not null default 0 check (usage_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, month_key)
);

create table if not exists public.campaign_history (
  id bigint generated by default as identity primary key,
  user_id text not null,
  prompt text not null,
  social_caption text not null,
  whatsapp_promo text not null,
  ad_copy text not null,
  marketing_tip text not null,
  created_at timestamptz not null default now()
);

create index if not exists campaign_history_user_created_idx
  on public.campaign_history (user_id, created_at desc);

alter table public.user_profiles enable row level security;
alter table public.campaign_usage enable row level security;
alter table public.poster_usage enable row level security;
alter table public.campaign_history enable row level security;

-- Marketa accesses these tables only from authenticated Next.js API routes
-- using the Supabase service-role key. No browser-facing policies are needed.
