create extension if not exists pgcrypto;

create table if not exists public.user_profiles (
  user_id text primary key,
  plan text not null default 'free'
    check (plan in ('free', 'starter', 'growth', 'pro')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.campaign_usage (
  id bigint generated by default as identity primary key,
  user_id text not null,
  month_key text not null check (month_key ~ '^\d{4}-\d{2}$'),
  usage_count integer not null default 0 check (usage_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, month_key)
);

create table if not exists public.poster_usage (
  id bigint generated by default as identity primary key,
  user_id text not null,
  month_key text not null check (month_key ~ '^\d{4}-\d{2}$'),
  usage_count integer not null default 0 check (usage_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, month_key)
);

create table if not exists public.campaign_history (
  id bigint generated by default as identity primary key,
  user_id text not null,
  prompt text not null,
  social_caption text not null,
  whatsapp_promo text not null,
  ad_copy text not null,
  marketing_tip text not null,
  created_at timestamptz not null default now()
);

create index if not exists campaign_history_user_created_idx
  on public.campaign_history (user_id, created_at desc);

alter table public.user_profiles enable row level security;
alter table public.campaign_usage enable row level security;
alter table public.poster_usage enable row level security;
alter table public.campaign_history enable row level security;

create table if not exists public.business_profiles (
  user_id text primary key,
  business_name text,
  business_type text,
  custom_business_type text,
  description text,
  target_audience text,
  location text,
  phone text,
  website text,
  instagram text,
  brand_voice text not null default 'Friendly',
  primary_color text not null default '#4f46e5',
  secondary_color text not null default '#0f172a',
  preferred_cta text,
  logo_url text,
  brand_images jsonb not null default '[]'::jsonb
    check (jsonb_typeof(brand_images) = 'array'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.business_profiles enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'brand-assets',
  'brand-assets',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Business profiles and brand uploads are accessed only from authenticated
-- Next.js API routes using the Supabase secret key.

-- Marketa accesses these tables only from authenticated Next.js API routes
-- using a Supabase secret key. No browser-facing policies are needed.
